language: ruby
rvm:
- 2.1.2
deploy:
  provider: heroku
  api_key:
    secure: SwVrny/w+HD2ziBqMVSGngt4HIHf3WRUF+WkW854JVY/VmFJst+6ce1gWfNvMXjm+WlRo9Zb3/CIn7JRyU9OuFKg/QbhIZWr7kybyKblYfG0BcqE2oOFSIqAOccwtqqJCnT1BGwfrRzh7hrlRCrrjfhp+HMMKoxNld863C8/AYw=
  strategy: git
  app: digi-foosball
  on:
    repo: BRKalow/digifoosball
before_script: bundle exec rake db:test:prepare
